// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZ0Y-TYJuZ2_F4cZE03LXJBj2YFeB-Lo',
    appId: '1:725185370198:web:6372f1220192c4642983f7',
    messagingSenderId: '725185370198',
    projectId: 'flutter-firebase-cianfa',
    authDomain: 'flutter-firebase-cianfa.firebaseapp.com',
    storageBucket: 'flutter-firebase-cianfa.appspot.com',
    measurementId: 'G-GC0PW8P578',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHLkXDhel6vCh1cFfe7bcBS4mfRj3U-c',
    appId: '1:725185370198:android:dc1a6d4e0fbad04d2983f7',
    messagingSenderId: '725185370198',
    projectId: 'flutter-firebase-cianfa',
    storageBucket: 'flutter-firebase-cianfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFK0GlAMMDxfeK3vCM__8Bpz8-FiUESn0',
    appId: '1:725185370198:ios:2cd15ca09a5ae2072983f7',
    messagingSenderId: '725185370198',
    projectId: 'flutter-firebase-cianfa',
    storageBucket: 'flutter-firebase-cianfa.appspot.com',
    iosBundleId: 'com.example.cianfafire',
  );

}